# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory to /app
WORKDIR /app

# Set an environment variable for the figure folder
ENV FIGURE_FOLDER $PWD/figures/

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
# RUN apt-get update -y
# RUN apt-get install -y libx11-dev
# RUN apt-get install -y python3-tk
RUN pip install --no-cache-dir -r requirements.txt

# Make the scripts directory the default path
ENV PATH="/app/scripts:${PATH}"

# Define the entry point
ENTRYPOINT ["python", "entrypoint.py"]
